blank_issues_enabled: false
contact_links:
  - name: Vagabond Hiatus Chart - Form
    url: https://docs.google.com/forms/d/e/1FAIpQLSeXHogBhJD-VX5XAUEpSb2-KSBHfJndBVbBuTvwpfnpk0TXqQ/viewform
    about: Please ask and answer questions here.
