name: Node.js CI

on:
  pull_request:
    branches: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sun
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Node.js with version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: sun/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
